---
apiVersion: v1
kind: Pod
metadata:
  name: pod0001
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: v0001
  volumes:
    - name: v0001
      persistentVolumeClaim:
        claimName: pvc0001
