---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: etcd
  name: etcd
spec:
  ports:
  - name: 2379-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: 2380-2380
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    app: etcd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  selector:
    matchLabels:
      app: etcd # has to match .spec.template.metadata.labels
  serviceName: "etcd"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: etcd # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: bitnami/etcd:3-debian-10
        env: 
          - name: ALLOW_NONE_AUTHENTICATION
            value: "yes"
        ports:
        - containerPort: 2379
        - containerPort: 2380
        volumeMounts:
        - name: etcd
          mountPath: /bitnami/etcd/data
  volumeClaimTemplates:
  - metadata:
      name: etcd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
