---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow

  claimRef:
    name: foo-pvc
    namespace: foo
  # Specify the relevant PersistentVolumeClaim in the claimRef field of the PV so that other PVCs can not bind to it.


  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
